version: '3'

services:
  vault:
    container_name: vault
    image: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: my-root-token
  resty:
    container_name: resty
    build: .
    depends_on:
    - vault
    ports:
    - "8080:8080"
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
    - "80:80"
